serd/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf.urls.i18n import i18n_patterns
from .views import (AddOffer, AddRequest, OfferUpdate, offer_list, request_list, request_update,  index, SuccessOffer,
                    SuccessRequest, UpdateRequestFilter, UpdateOfferFilter, hotel_list, OfferAutocomplete, statistics, 
                    InternalAddOffer, internal_add_housingrequest, profile_view, profile_list, UpdateProfile, invoice_view, hotel_add_housingrequest,
                    AddPate, paten_list )
from django.conf import settings
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),

    path("accounts/", include("django.contrib.auth.urls")),
    path('requests/',request_list, name='requests'),
    path('offers/', offer_list, name='offers'),
    path('offers/edit/<offer_id>', login_required(OfferUpdate.as_view())),
    path('requests/edit/<request_id>', request_update),
    path('request_filter', login_required(UpdateRequestFilter.as_view()), name="request_filter"),
    path('offer_filter', login_required(UpdateOfferFilter.as_view()), name="offer_filter"),
    path('',index, name='index'),
    path('hotels/', hotel_list, name='hotels'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('autocomplete-offer', login_required(OfferAutocomplete.as_view()), name='offer-autocomplete'),
    path('statistics/', statistics, name='statistics'),
    path('add_offer/intern', login_required(InternalAddOffer.as_view()), name='internal_add_offer'),
    path('add_request/intern', internal_add_housingrequest, name='internal_add_request'),
    path('profiles/<profile_id>/', profile_view, name='profile_view'),
    path('profiles/', profile_list, name='profile_list'),
    path('profiles_edit/', login_required(UpdateProfile.as_view()), name='profile_edit'),
    path('invoices', invoice_view, name='invoice'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(success_url='/'),
        name='password_reset_confirm',
    ),
    path('add_request/hotel/', hotel_add_housingrequest, name='add_request_hotel'),
    path('paten/', paten_list, name='paten')
   
]
urlpatterns += i18n_patterns(
    path('add_request/',AddRequest.as_view(),name='add_request'),
    path('add_offer/', AddOffer.as_view(), name='add_offer'),
    path('success_request/<request_id>', SuccessRequest.as_view(), name='success_request'),
    path('success_offer/<offer_id>', SuccessOffer.as_view(), name='success_offer'),
    path('add_pate', AddPate.as_view(), name='add_pate'),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serd/models.py
from django.conf import settings
from django.db import models
from multiselectfield import MultiSelectField
from django.core.validators import validate_email
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from .choices import CURRENT_ACCOMODATION, FOOD_CHOICES, HOTEL_STATE, LANGUAGE_CHOICE, LIVING_WITH, MENTOR_STATE, OFFER_SORT, PRIORITY_CHOICE, LIVING_WITH, OFFER_STATE, PETS, REQUEST_SORT, REQUEST_STATE, SORT_DIRECTION
from .validators import validate_not_empty, validate_plz, validate_phone, validate_not_negative



User = get_user_model()


class RequestFilter(models.Model):
    num_min = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Personen von")
    num_max = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Personen bis")
    split = models.BooleanField(null=True, verbose_name="Teilbar")
    current_housing = models.CharField(blank=True, choices=CURRENT_ACCOMODATION, verbose_name="Aktuelle Unterbringung", max_length=64)
    pets = MultiSelectField(choices=PETS, null=True, blank=True,  verbose_name="Haustiere")
    languages = MultiSelectField(choices=LANGUAGE_CHOICE, null=True, blank=True, verbose_name="Sprachen")
    accessability_needs = models.BooleanField(null=True,  verbose_name="Barrierefrei")
    priority = MultiSelectField(choices=PRIORITY_CHOICE, null=True, blank=True, verbose_name="Priorität")
    state = MultiSelectField(choices=REQUEST_STATE, null=True, blank=True, verbose_name="Status")
    no_handler = models.BooleanField(null=True, verbose_name="Kein Sachbearbeiter")
    case_handler = models.ForeignKey(to=User, on_delete=models.SET_NULL,  null=True, blank=True)
    sort = models.CharField(choices=REQUEST_SORT, default='number', verbose_name='Sortierung', max_length=64)
    sort_direction = models.CharField(choices=SORT_DIRECTION, default='asc', verbose_name='Auf/Absteigend', max_length=64)


class OfferFilter(models.Model):
    num_min = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Personen von")
    num_max = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Personen bis")
    PLZ = models.CharField(max_length=5, blank=True, verbose_name='PLZ')
    city = models.CharField(max_length=128, blank=True, verbose_name='Ort')
    cost_min = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Kosten von')
    cost_max = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Kosten bis')
    language = MultiSelectField(choices=LANGUAGE_CHOICE, blank=True, verbose_name="Sprachen")
    spontan = models.BooleanField(null=True,  verbose_name='Spontan')
    limited = models.BooleanField(null=True, verbose_name='Begrenzt verfügbar')
    appartment = models.BooleanField(null=True, verbose_name='Eigene Wohnung')
    pets = MultiSelectField(choices=PETS, null=True, blank=True, verbose_name='Haustiere')
    accessability = models.BooleanField(null=True, verbose_name="Barrierefrei")
    state = MultiSelectField(choices=OFFER_STATE, verbose_name='Status', null=True, blank=True)
    for_free = models.BooleanField(null=True, verbose_name='Gratis')
    sort = models.CharField(choices=OFFER_SORT, default='number', verbose_name='Sortierung', max_length=64)
    sort_direction = models.CharField(choices=SORT_DIRECTION, default='asc', verbose_name='Auf/Absteigend', max_length=64)

class Profile(models.Model):
    number = models.AutoField(primary_key=True)
    account = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Account")
    name = models.CharField(max_length=64, blank=True)
    mail = models.CharField(max_length=256, validators=[validate_email],verbose_name= "E-Mail-Adresse", blank=True)
    phone = models.CharField(max_length=50, validators=[validate_phone], verbose_name= "Telefonnummer", blank=True)
    telegram = models.CharField(max_length=64, verbose_name="Telegram", blank=True)
    threema = models.CharField(max_length=64, verbose_name="Threema", blank=True)
    whatsapp = models.BooleanField(verbose_name="Whatsapp")
    signal = models.BooleanField(verbose_name="Signal")
    languages = MultiSelectField(choices=LANGUAGE_CHOICE, verbose_name="Sprachkenntnisse", null=True, blank=True)
    comment = models.CharField(max_length=128, verbose_name="Kommentar", blank=True)
    request_filter = models.OneToOneField(to=RequestFilter, null=True, blank=True, on_delete=models.SET_NULL)
    offer_filter = models.OneToOneField(to=OfferFilter, null=True, blank=True, on_delete=models.SET_NULL)
    def __str__(self) -> str:
        return self.account.username



class AnnotationManager(models.Manager):

    def __init__(self, **kwargs):
        super().__init__()
        self.annotations = kwargs

    def get_queryset(self):
        return super().get_queryset().annotate(**self.annotations)

class  HousingRequest(models.Model):
    number = models.AutoField(primary_key=True)
    last_name = models.CharField(max_length=128, verbose_name=_("Nachname"),blank=True)
    given_name = models.CharField(max_length=128, verbose_name=_("Vorname"), blank=True)
    name_slug = models.CharField(max_length=256, blank=True, default="")
    phone = models.CharField(max_length=50, validators=[validate_phone], verbose_name=_("Telefonnummer"), blank=True)
    mail = models.CharField(max_length=256, validators=[validate_email],verbose_name=_("E-Mail-Adresse"), blank=True)
    representative = models.CharField(max_length=256, blank=True, verbose_name=_("Name einer stellvertretenden Person"), help_text=_("falls zutreffend"))
    repr_phone = models.CharField(max_length=256, blank=True, validators=[validate_phone], verbose_name=_("Telefonnummer der stellvertretenden Person"))
    repr_mail = models.CharField(max_length=256, blank=True, validators=[validate_email], verbose_name=_("E-Mail-Adresse der stellvertretenden Person"))
    adults = models.PositiveSmallIntegerField(verbose_name=_("Anzahl der Erwachsenen und Kindern ab 12 Jahren"), validators=[validate_not_negative], blank=True)
    children = models.PositiveSmallIntegerField(verbose_name=_("Anzahl der Kinder unter 12"), validators=[validate_not_negative], blank=True)
    who = models.CharField(max_length=512, blank=True)
    split = models.BooleanField(verbose_name=_("Ab fünf Personen: Gruppe darf geteilt werden"), help_text=_("notfalls kann eine Unterbringung in zwei Unterkünften erfolgen"))
    current_housing = models.CharField(choices=CURRENT_ACCOMODATION, max_length=128, verbose_name=_("Wo sind Sie aktuell untergebracht?"), blank=True)
    arrival_date = models.DateField(verbose_name=_("Wann kommen Sie in Regensburg an oder seit wann sind Sie da?"), null=True)
    pets = MultiSelectField(choices=PETS, verbose_name=_("Welche Haustiere haben Sie?"), null=True)
    pet_number = models.PositiveSmallIntegerField(verbose_name=_("Wie viele Haustiere haben Sie?"), validators=[validate_not_negative], blank=True, null=True)
    car = models.BooleanField(verbose_name=_("Haben Sie ein Auto?"))
    languages = MultiSelectField(choices=LANGUAGE_CHOICE, verbose_name=_("Sprachkenntnisse"), null=True, blank=True)
    additional_languages = models.CharField(verbose_name=_("Weitere Sprachen"), max_length=64, blank=True)
    vaccination = models.BooleanField(verbose_name=_("Sind alle Personen in Ihrer Gruppe vollständig gegen COVID-19 geimpft?"))
    accessability_needs = models.BooleanField(_("Wird eine barrierefreie Wohnung benötigt?"))
    can_pay = models.BooleanField(verbose_name=_("Können Sie für Ihre Unterkunft zahlen?"), help_text=_("Keine Voraussetzung für die Vermittlung einer privaten Notunterkunft"))
    case_handler = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Sachbearbeiter:in"))
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64, verbose_name=_("Priorität"), blank=True)
    placed_at = models.ForeignKey('Offer', on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Vermitttelt an"))
    state = models.CharField(choices=REQUEST_STATE, verbose_name=_("Status"), default="new", max_length=64)
    private_comment = models.CharField(blank=True, null=True,  default="", max_length=1024)
    created_at = models.DateField(auto_now_add=True)
    possible_hosts = models.ManyToManyField(to='Offer', related_name="possible_guests", blank=True, verbose_name="Mögliche Gastgeber")
    smoker = models.BooleanField(verbose_name=_("Raucht jemand aus Ihrer Gruppe?"))
    profession = models.CharField(verbose_name=_("Welchen Beruf üben Sie aus?"), max_length=64, null=True, blank=True)
    _persons = None

    objects = AnnotationManager(persons=models.F('adults')+models.F('children'))
    def __str__(self):
        return "_".join([str(self.number),self.last_name, self.given_name])
    class Meta:
        app_label ='serd'

class Offer(models.Model):
    number = models.AutoField(primary_key=True)
    last_name = models.CharField(max_length=128, verbose_name=_("Nachname"), blank=True, validators=[validate_not_empty])
    given_name = models.CharField(max_length=128, verbose_name=_("Vorname"), blank=True)
    plz = models.CharField(max_length=5, validators=[validate_plz], verbose_name=_("Postleitzahl"), blank=True)
    total_number = models.PositiveSmallIntegerField(verbose_name=_("Anzahl der Personen, die in dieser Wohnung eine Unterkunft finden können."), validators=[validate_not_negative], blank=True)
    children_number = models.PositiveSmallIntegerField(blank=True, verbose_name=_("Anzahl der zuvor genannten Plätze, die nur für Kinder unter 12 geeignet sind."), validators=[validate_not_negative])
    street = models.CharField(max_length=256, blank=True, verbose_name=_("Straße, Hausnummer (optional)"))
    city = models.CharField(max_length=256, verbose_name=_("Ort"), blank=True)
    mail = models.CharField(max_length=256, validators=[validate_email], verbose_name=_("E-Mail-Adresse"), blank=True)

templates/serd/form_snippet.html
{% for field in form %}
<div class="fieldWrapper form-group row m-1">
    {{ field.errors }}
    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">
        {{ field.label}}
    </label>
    <div class="col-sm-10 my-auto">
        {{ field }}
    </div>
    
    {% if field.help_text %}
    <p class="help">{{ field.help_text|safe }}</p>
    {% endif %}
</div>
{% endfor %}

templates/serd/hotel_list.html
{# Load the tag library #}
{% load bootstrap5 %}
{% load static %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<html>
<head>
<style>
    .header{
        position:sticky;
        top:0;
        z-index:1;
    }

    .tableFixHead { overflow: auto; height: 90vh; }

    #table-head {
        background-color:#FFFFFF; 
    }

    table  { border-collapse: collapse; width: 100%; }
</style>
<title>Hotels - SERD</title>
<link rel="icon" type="image/x-icon" href="{% static 'logo.png' %}">
</head>

<body>
    Space Eye - Notunterkunftsvermittlung - Hotels
<div class="tableFixHead">
    <table class="table">
    <thead class="header" id="table-head">
        <th>ID</th>
        <th>Name</th>
        <th>Adresse</th>
        <th>Status</th>
        <th>Ansprechpartner Hotel</th>
        <th>Telefon</th>
        <th>E-Mail</th>
        <th>Zuständig Meldung</th>
        <th>Team Gesamt</th>
        <th>Verpflegung</th>
        <th>Kosten</th>
        <th>Belegung Aktuell</th>
        <th>Betten</th>
        <th>Betten frei</th>
        <th>Info</th>
        <th></th>
    </thead>
    <tbody>
    {% for hotel in dataset %}
        {%if hotel.state == "active"%}    
            <tr style="background-color:white">
        {%elif hotel.state == "open" %}
            <tr style="background-color:yellow">
        {%elif hotel.state == "full" %}
            <tr style="background-color:red">
        {%elif hotel.state == "passive" %}
                <tr style="background-color:darksalmon">
        {%endif%}

           <td> {{hotel.number}}</td>
           <td> {{hotel.name}}</td>
           <td> {{hotel.address}}</td>
            <td> {{hotel.get_state_display}}</td>
            <td>
                {%for partner in hotel.ansprechpartner.all %}
                    {{partner.name}}<br>
                {% endfor %}
            </td>
            <td>
                {%for partner in hotel.ansprechpartner.all %}
                    {{partner.tel}}<br>
                {% endfor %}
            </td>
            <td>
                {%for partner in hotel.ansprechpartner.all %}
                    {{partner.mail}}<br>
                {% endfor %}
            </td>
            <td>
                {%if hotel.responsible %}
                <a href="{% url 'profile_view' hotel.responsible.id %}" style="color: black; text-decoration: underline;">
                    {{hotel.responsible}}
                </a>
                {%endif%}
            </td>
            <td>
                {% for member in hotel.team_gesamt.all %}
                    <a href="{% url 'profile_view' member.id %}" style="color: black; text-decoration: underline;">
                        {{ member }}
                    </a>
                {% endfor %}
            </td>
            <td>
                {{ hotel.get_food_display }}
            </td>
            <td>
                {{ hotel.cost }}
            </td>
            <td>
                {% for request in hotel.requests.all %}
                <a href="/requests/edit/{{request.number}}" style="color:black; text-decoration:underline">
                {{request}}
            </a>&emsp;
                {% endfor %}
                {%if hotel.departing%}<h5>Abreisend:</h5> {%endif%}
                {% for request in hotel.departing.all %}
                <a href="/requests/edit/{{request.number}}" style="color:black; text-decoration:underline">
                    {{request}}
                </a>&emsp;
                    {% endfor %}
            </td>
            <td>
                {{ hotel.beds }}
            </td>

            <td>
                {{hotel.beds_free }}
            </td>
            <td>
                {{ hotel.info|linebreaks }}
            </td>
           </tr>
        {% endfor %}
        </tbody>
    
    
    </tbody>
    </table>
</div>

<div class="d-flex flex-row">

    <div class="m-3">
        {% url 'logout' as logout_url%}
        {% bootstrap_button "Log out" button_type="link" href=logout_url button_class="btn-danger" %}
    </div>
    <div class="m-3">
        {% url 'index' as index_url%}
        {% bootstrap_button "Startseite" button_type="link" href=index_url button_class="btn-secondary" %}
    </div>
</div>
</body>
</html>

templates/serd/offer_list.html
{# Load the tag library #}
{% load bootstrap5 %}
{% load static %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<html>
<head>
<style>
    .header{
        position:sticky;
        top:0;
        z-index:1;
    }

    .tableFixHead { overflow: auto; height: 90vh; }

    #table-head {
        background-color:#FFFFFF; 
    }

    table  { border-collapse: collapse; width: 100%; }

    .sticky-col {
      position: -webkit-sticky;
      position: sticky;
      background-color: white;
    }
    
    .first-col {
      width: 100px;
      min-width: 100px;
      max-width: 100px;
      left: 0px;
    }
    
    .second-col {
      width: 150px;
      min-width: 150px;
      max-width: 150px;
      left: 100px;
    }

    .comment-col {
      width: 35em;
      min-width: 35em;
    }
</style>
<title>Housig offers - SERD</title>
<link rel="icon" type="image/x-icon" href="{% static 'logo.png' %}">

</head>

<body>
  Space Eye - Notunterkunftsvermittlung - Angebote
  &nbsp;{{dataset |length}} Ergebnisse
  <div class="tableFixHead">
    <table class="table">
    <thead class="header" id="table-head">
        <th class="sticky-col first-col" style="background-color: white">ID</th>
        <th class="sticky-col second-col" style="background-color: white">Name</th>
        <th>PLZ</th>
        <th>Ort</th>
        <th>Gesamtanzahl der Personen</th>
        <th>davon Kinder unter zwölf</th>
        <th>Gratis</th>
        <th>Kosten</th>
        <th>Sprachen</th>
        <th>Barrierefrei</th>
        <th>Haustiere</th>
        <th class="comment-col">Kommentar</th>
        <th class="comment-col">Interner Kommentar</th>
        <th>Straße</th>
        <th>Tel</th>
        <th>mail</th>
        <th>spontan</th>
        <th>verfügbar ab</th>
        <th>begrenzt verfügbar</th>
        <th>verfügbar bis</th>
        <th>ÖPNV</th>
        <th>Zimmer</th>
        <th>Eigene Wohnung</th>
        <th>Wohnsituation</th>
        <th>Status</th>
        <th>Vermittelt</th>
        <th>Stadt</th>
      </thead>
      <tbody>
      {% for data in dataset %} {%if data.state == "new"%}
      <tr  style="background-color: white">
        <td class="sticky-col first-col" style="background-color: white">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: white">{{ data.given_name}} {{data.last_name}}</td>
      {%elif data.state == "contacted" %}
      

      <tr style="background-color: yellow">
        <td class="sticky-col first-col" style="background-color: yellow">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: yellow">{{ data.given_name}} {{data.last_name}}</td>
      {%elif data.state == "request_contact" %}
      

      <tr style="background-color: lightblue">
        <td class="sticky-col first-col" style="background-color: lightblue">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: lightblue">{{ data.given_name}} {{data.last_name}}</td>
      {%elif data.state == "stale" %}
      

        
      <tr style="background-color: lightgray">
        <td class="sticky-col first-col" style="background-color: lightgrey">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: lightgrey">{{ data.given_name}} {{data.last_name}}</td>
      {%elif data.state == "arrived" %}
      

      <tr style="background-color: green">
        <td class="sticky-col first-col" style="background-color: green">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: green">{{ data.given_name}} {{data.last_name}}</td>
        {%elif data.state == "free" %}
      

      <tr style="background-color: orange">
        <td class="sticky-col first-col" style="background-color: orange">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: orange">{{ data.given_name}} {{data.last_name}}</td>
        {%elif data.state == "reserved" %}
      

      <tr style="background-color: red">
        <td class="sticky-col first-col" style="background-color: red">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: red">{{ data.given_name}} {{data.last_name}}</td>
       {%elif data.state == "no" %}
       <tr style="background-color: darkgray">
        <td class="sticky-col first-col" style="background-color: darkgray">{{data.number}}</td>
        <td class="sticky-col second-col" style="background-color: darkgray">{{ data.given_name}} {{data.last_name}}</td>
        {%endif%}
        <td>
          <div id="{{data.number}}"></div>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.plz}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.city}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}"
            >{{data.total_number}}</span
          >
          <td>
            <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}"
              >{{data.children_number}}</span
            >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.for_free|yesno:'Ja,Nein'}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.cost}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.language}}
            {% if data.additional_languages %}
              <br> {{data.additional_languages}}
            {% endif %}
            </span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.accessability|yesno:'Ja,Nein'}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.pets}}</span
          >
        </td>
        <td class="comment-col">
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}">
            {{data.comment}}</span
          >
        </td>
        <td  class="comment-col">
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}">
            {{data.private_comment}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.street}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.phone}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.mail}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.spontan|yesno:'Ja,Nein'}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.available_from}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.limited_availability |yesno:'Ja,Nein'}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.available_until}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.public_transport|yesno:'Ja,Nein'}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.rooms}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.seperate_appartment|yesno:'Ja,Nein'}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.get_living_with_display}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{{data.get_state_display}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            >{% for req in data.housingrequest_set.all %}<a href="/requests/edit/{{req.number}}" style="color:black; text-decoration:underline"> {{ req }}</a> <br> {% endfor%}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}">
            {{data.by_municipality |yesno:'Ja,Nein'}}</span
          >
        </td>
        <td>
          <span title="{{data.number }} {{ data.given_name}}, {{data.last_name}}"
            ><a href="/offers/edit/{{data.number}}"style="color:black; text-decoration:underline">edit </a></span
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>

  <div class="d-flex flex-row">
    <div class="m-3">
        {% url 'offer_filter' as offer_filter_url %}
        {% bootstrap_button "Filter" button_type="link" href=offer_filter_url button_class="btn-primary" %}
    </div>
    <div class="m-3">
        {% url 'logout' as logout_url%}
        {% bootstrap_button "Log out" button_type="link" href=logout_url button_class="btn-danger" %}
    </div>
    <div class="m-3">
        {% url 'index' as index_url%}
        {% bootstrap_button "Startseite" button_type="link" href=index_url button_class="btn-secondary" %}
    </div>
  </div>
</body>

templates/serd/success_offer.html
{% load i18n %}
{% load static %}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}

<head>
    <title>Erfolg </title>
    <link rel="icon" type="image/x-icon" href="{% static 'logo.png' %}">
</head>
<body>
{% blocktrans with nr=view.kwargs.offer_id %}
Das Wohnungsangebot mit der ID {{ nr }} wurde erfolgreich gespeichert. <br>
{% endblocktrans %}
<br>
<div style="margin-left:20px;"><a href="https://space-eye.org"><button class="btn" role="button" style="background-color: #007194;">space-eye.org</button></a></div>
</body>